name: Deploy Pelican site to GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  Deploy:
    uses: brighamskarda/brighamskarda.github.io/.github/workflows/pelican.yml@main
    permissions:
      contents: read
      pages: write
      id-token: write