name: Deploy

on:
  # Trigger the workflow on push on main branch,
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: 'true'
    - uses: rehanhaider/pelican-to-github-pages@v1.3.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
